// Code generated by tools. DO NOT EDIT!
package status_error

import (
	"fmt"
	"github.com/shrewx/ginx/pkg/i18nx"
	"github.com/shrewx/ginx/pkg/statuserror"
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"strconv"
)

func init() {
	i18nx.RegisterHooks(RegisterErrorMessages)
}

func (v StatusError) WithParams(params map[string]interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(params)
}

func (v StatusError) WithField(key interface{}, value string) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithField(key, value)
}

func (v StatusError) Localize(manager *i18nx.Localize, lang string) i18nx.I18nMessage {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Localize(manager, lang)
}

func (v StatusError) LocalizeValue(value interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(map[string]interface{}{"Value": value})
}

func (v StatusError) LocalizeData(data map[string]interface{}) statuserror.CommonError {
	return statuserror.NewStatusErr(v.Key(), v.Code()).WithParams(data)
}

func (v StatusError) StatusCode() int {
	return statuserror.NewStatusErr(v.Key(), v.Code()).StatusCode()
}

func (v StatusError) Key() string {
	switch v { 
	case BadRequest:
		return "BadRequest"
	case InvalidUserID:
		return "InvalidUserID"
	case Unauthorized:
		return "Unauthorized"
	case Forbidden:
		return "Forbidden"
	case NotFound:
		return "NotFound"
	case UserNotFound:
		return "UserNotFound"
	case Conflict:
		return "Conflict"
	case StatusBadGateway:
		return "StatusBadGateway"
	}
	return "UNKNOWN"
}

func (v StatusError) Prefix() string {
	return "error_codes"
}

func (v StatusError) ID() string {
	if v.Prefix() == "" {
		return strconv.FormatInt(int64(v.Code()), 10)
	}
	return v.Prefix() + "." + strconv.FormatInt(int64(v.Code()), 10)
}

func (v StatusError) Code() int64 {
	return int64(v)
}

func (v StatusError) Error() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Error()
}

func (v StatusError) Value() string {
	return statuserror.NewStatusErr(v.Key(), v.Code()).Value()
}

func GetStatusErrorMap() map[string]map[StatusError]string {
	return map[string]map[StatusError]string{
		"en": {
			BadRequest: "bad request",
			InvalidUserID: "invalid user ID, must be a positive integer",
			Unauthorized: "unauthorized",
			Forbidden: "forbidden",
			NotFound: "not found",
			UserNotFound: "user not found, user ID: {{.UserID}}",
			Conflict: "conflict",
			StatusBadGateway: "operation failed, please retry later",
			
		},
		"zh": {
			BadRequest: "请求参数错误",
			InvalidUserID: "用户ID无效，必须为正整数",
			Unauthorized: "未授权，请先授权",
			Forbidden: "禁止操作",
			NotFound: "资源未找到",
			UserNotFound: "用户不存在，用户ID：{{.UserID}}",
			Conflict: "资源冲突",
			StatusBadGateway: "操作存在异常，请稍后重试",
			
		},
		
	}
}

func RegisterErrorMessages() {
	errorMap := GetStatusErrorMap()
	for lang, messages := range errorMap {
		var i18nMessages []*i18n.Message
		for key, message := range messages {
			i18nMessages = append(i18nMessages, &i18n.Message{ID: fmt.Sprintf("%s.%s", lang, key.ID()), Other: message})
		}
		i18nx.AddMessages(lang, i18nMessages)
	}
}
